### ISSUE TITLE
Create Character

### ISSUE THREAD

**Issue by Todor-Shishmanov** [Todor-Shishmanov/DnD_tool#2]
Everything that a DnD character has is (basically) included in the character sheet. Implement a class that can store and manipulate that data.

**Tasks:**
- [x] Concept Docs
- [ ] Tests
- [ ] Implementation
- [ ] Tech Docs

**Comment by Todor-Shishmanov** [comment]
I added [Character](https://app.nuclino.com/Team-ToMi/DnD-Tool/-Character-f5839992-9a55-4275-807e-557efff048bb) concept documentation outlining the basics around a character. If more details are required I can add them. The problem is I cannot (and should not) just dumb the whole PhB (player's handbook). @mirela-manoleva

**Comment by mirela-manoleva** [comment]
Good description overall. We may need to add some info later but for now, it's enough.
Aproved!
