### ISSUE TITLE
Add documentation overview

### ISSUE THREAD

**Issue by Todor-Shishmanov** [Todor-Shishmanov/DnD_tool#3]
Add overview to the project

**Tasks:**
- [x] Docs

**Comment by Todor-Shishmanov** [comment]
I added [Project overview](https://app.nuclino.com/Team-ToMi/DnD-Tool/-Project-Overview-6556c65a-d8a9-488d-8a82-7ff8a16cd599) and [DnD Rulebooks](https://app.nuclino.com/Team-ToMi/DnD-Tool/-DnD-Rule-Books-Supported-ab75c88a-02fc-46a1-97e9-820b603cca07) . There isn't much there but I think it's enough for now.

**Comment by mirela-manoleva** [comment]
I like the picture and the page structure very much!
Approved!
